-- 1. Tạo bảng lưu trữ lịch sử chat
-- Dùng UNLOGGED table để tăng tốc độ và giảm ghi đĩa (vì dữ liệu chỉ cần tồn tại 10 phút)
CREATE UNLOGGED TABLE IF NOT EXISTS chat_history (
    id bigint generated by default as identity primary key,
    session_id text not null,
    role text not null,
    content text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Tạo Index để tìm kiếm và xóa nhanh hơn
CREATE INDEX IF NOT EXISTS idx_chat_history_session_id ON chat_history(session_id);
CREATE INDEX IF NOT EXISTS idx_chat_history_created_at ON chat_history(created_at);

-- 3. Tạo Function xóa tin nhắn cũ (TTL 10 phút)
CREATE OR REPLACE FUNCTION delete_old_chat_history()
RETURNS TRIGGER AS $$
BEGIN
  -- Xóa các tin nhắn cũ hơn 10 phút
  DELETE FROM chat_history
  WHERE created_at < NOW() - INTERVAL '10 minutes';
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 4. Tạo Trigger để TỰ ĐỘNG KÍCH HOẠT mỗi khi có tin nhắn mới (INSERT)
DROP TRIGGER IF EXISTS trigger_delete_old_chat ON chat_history;
CREATE TRIGGER trigger_delete_old_chat
AFTER INSERT ON chat_history
FOR EACH ROW
EXECUTE FUNCTION delete_old_chat_history();

-- 5. Bảng theo dõi sức khỏe Model (Circuit Breaker Pattern)
-- Lưu trạng thái "ốm" của model. Nếu model lỗi, ghi vào đây để tạm ngưng sử dụng trong 20 phút.
CREATE UNLOGGED TABLE IF NOT EXISTS model_health (
    model_id text primary key,
    last_failure_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE INDEX IF NOT EXISTS idx_model_health_last_failure ON model_health(last_failure_at);

-- 6. Function dọn dẹp Model đã "hết án treo giò"
CREATE OR REPLACE FUNCTION clean_expired_model_health()
RETURNS TRIGGER AS $$
BEGIN
  DELETE FROM model_health
  WHERE last_failure_at < NOW() - INTERVAL '20 minutes';
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 7. Trigger tự động dọn dẹp mỗi khi có báo cáo lỗi mới
DROP TRIGGER IF EXISTS trigger_clean_model_health ON model_health;
CREATE TRIGGER trigger_clean_model_health
AFTER INSERT OR UPDATE ON model_health
FOR EACH ROW
EXECUTE FUNCTION clean_expired_model_health();

-- 8. Bảng lưu trữ Cache Câu trả lời
CREATE TABLE IF NOT EXISTS qa_cache (
    id bigint generated by default as identity primary key,
    question_text text unique not null,
    answer_text text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE INDEX IF NOT EXISTS idx_qa_cache_text ON qa_cache(question_text);

-- 9. Bảng giới hạn tần suất gọi API (Rate Limiting)
CREATE TABLE IF NOT EXISTS api_rate_limits (
    ip text primary key,
    request_count int default 1,
    last_request_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE INDEX IF NOT EXISTS idx_rate_limit_time ON api_rate_limits(last_request_at);

-- 10. Function tự động dọn dẹp các IP đã lâu không gọi (TTL 1 giờ)
CREATE OR REPLACE FUNCTION clean_expired_rate_limits()
RETURNS TRIGGER AS $$
BEGIN
  DELETE FROM api_rate_limits
  WHERE last_request_at < NOW() - INTERVAL '1 hour';
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 11. Trigger tự động dọn dẹp
DROP TRIGGER IF EXISTS trigger_clean_rate_limits ON api_rate_limits;
CREATE TRIGGER trigger_clean_rate_limits
AFTER INSERT OR UPDATE ON api_rate_limits
FOR EACH ROW
EXECUTE FUNCTION clean_expired_rate_limits();

-- 12. CÀI ĐẶT DỌN DẸP CHỦ ĐỘNG (PROACTIVE CLEANUP) - DÙNG PG_CRON
-- Việc này giúp xóa dữ liệu rác ngay cả khi không có người truy cập trang web.
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- Xếp lịch dọn dẹp định kỳ mỗi 10 phút
SELECT cron.schedule('db-cleanup-task', '*/10 * * * *', $$
  DELETE FROM chat_history WHERE created_at < NOW() - INTERVAL '10 minutes';
  DELETE FROM model_health WHERE last_failure_at < NOW() - INTERVAL '20 minutes';
  DELETE FROM api_rate_limits WHERE last_request_at < NOW() - INTERVAL '1 hour';
$$);
